### ISSUE TITLE
Use standard electropherogram DNA colours

### ISSUE THREAD

**Issue by gringer** [koelling/dnacol#2]
These are the base colours I'm most familiar with seeing:

A-green
C-blue
G-gold
T-red

https://en.wikipedia.org/wiki/Electropherogram [where gold is replaced with black for visibility purposes]

**Comment by koelling** [comment]
In version 0.4, I have now added a second DNA colormap with the colors you suggested. You should now be able to upgrade to this version using `pip install dnacol --upgrade`.

Once you have upgraded, you can set the colormap to use for DNA sequences using a config file in your home directory called `.dnacol`. To use the colors you suggested, you would add this line to the config file:

    dna_colormap: gbyr
