### ISSUE TITLE
Protein coloring

### ISSUE THREAD

**Issue by lucyforrest** [koelling/dnacol#3]
Color for proteins too, please! (hydrophobic vs hydrophilic vs charged is most important, if you want a simple scale)

**Comment by koelling** [comment]
Thank you for your suggestion, I will try to add this in the next version! What kind of file format would these sequences usually come in? FASTA? And is there already a standard color scheme for this that we should use?

**Comment by lucyforrest** [comment]
Yes, Fasta. You might check jalview and weblogo for some standard color schemes.

Thanks!!!
Lucy

===================
Dr. Lucy R Forrest, DPhil
NIH-NINDS
Porter Neuroscience Building
35 Convent Dr, Room 3D991
Bethesda MD 20892-3761
USA
Tel: 301-402-2012
Cell: 301-335-7392
Web: www.forrestlab.org
Twitter: @lucyrforrest

**Comment by gringer** [comment]
I've been using the RasMol colour scheme for my protein sequences:

http://life.nthu.edu.tw/~fmhsu/rasframe/COLORS.HTM

**Comment by koelling** [comment]
Made a first test version of this - would this be something like what you are looking for?

![screen shot 2017-08-25 at 15 38 14](https://user-images.githubusercontent.com/369559/29718686-80f4bcfa-89ab-11e7-953e-90c35506898e.png)

**Comment by lucyforrest** [comment]
Yeah! Cool!

**Comment by koelling** [comment]
I have added a new `pcol` command to version 0.4, which is now on pip! You should be able to upgrade using `pip install dnacol --upgrade`.
